-- VeloxShip Supabase schema for public.volex
-- Run this in the Supabase SQL editor

create table if not exists public.volex (
  id bigint generated by default as identity primary key,
  tracking_code text unique,
  user_id text,
  role text,
  full_name text,
  email text,
  phone text,
  address text,
  shipment_title text,
  weight numeric,
  origin text,
  destination text,
  status text default 'Pending',
  current_location text,
  movement_history text,
  estimated_delivery timestamptz,
  paused_reason text,
  created_at timestamptz default now(),
  password text,
  time timestamptz default now()
);

create index if not exists volex_tracking_code_idx on public.volex (tracking_code);
create index if not exists volex_email_idx on public.volex (email);
create index if not exists volex_created_at_idx on public.volex (created_at desc);

alter table public.volex enable row level security;

drop policy if exists "Allow public select on volex" on public.volex;
create policy "Allow public select on volex"
  on public.volex
  for select
  using (true);

drop policy if exists "Allow public insert on volex" on public.volex;
create policy "Allow public insert on volex"
  on public.volex
  for insert
  with check (true);

drop policy if exists "Allow admin-role rows to update on volex" on public.volex;
create policy "Allow admin-role rows to update on volex"
  on public.volex
  for update
  using (lower(coalesce(role, '')) = 'admin')
  with check (lower(coalesce(role, '')) = 'admin');
