-- VeloxShip Supabase schema
-- Includes:
-- 1) Existing lightweight user table (public.volex)
-- 2) New shipment table (public.shipment)
-- 3) New movement timeline table (public.movement_history)
-- 4) Required tracking indexes and basic policies

create extension if not exists pgcrypto;

create table if not exists public.volex (
  id bigint generated by default as identity primary key,
  tracking_code text unique,
  user_id text,
  role text,
  full_name text,
  email text,
  phone text,
  address text,
  shipment_title text,
  weight numeric,
  origin text,
  destination text,
  status text default 'Pending',
  current_location text,
  movement_history text,
  estimated_delivery timestamptz,
  paused_reason text,
  created_at timestamptz default now(),
  password text,
  time timestamptz default now()
);

create index if not exists volex_tracking_code_idx on public.volex (tracking_code);
create index if not exists volex_email_idx on public.volex (email);
create index if not exists volex_created_at_idx on public.volex (created_at desc);

create table if not exists public.shipment (
  id bigint generated always as identity primary key,
  tracking_code text not null unique,
  user_id text,
  full_name text,
  email text,
  phone text,
  address text,
  shipment_title text not null,
  product_category text default 'General cargo',
  product_description text,
  quantity integer default 1,
  weight numeric default 1,
  value_usd numeric default 0,
  origin text not null,
  destination text not null,
  status text not null default 'processing',
  current_location text not null,
  estimated_delivery timestamptz,
  departure_time timestamptz,
  paused_reason text,
  notes text,
  shipping_mode text default 'Express',
  priority text default 'Priority',
  confirmed_by_customer boolean default false,
  current_step integer default 0,
  movement_plan jsonb not null default '[]'::jsonb,
  next_movement_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists shipment_tracking_code_idx on public.shipment (tracking_code);
create index if not exists shipment_user_id_idx on public.shipment (user_id);
create index if not exists shipment_email_idx on public.shipment (email);
create index if not exists shipment_status_idx on public.shipment (status);
create index if not exists shipment_next_movement_at_idx on public.shipment (next_movement_at);
create index if not exists shipment_created_at_idx on public.shipment (created_at desc);

create table if not exists public.movement_history (
  id bigint primary key generated always as identity,
  shipment_id bigint references public.shipment(id) on delete cascade,
  location text not null,
  status text not null,
  note text,
  created_at timestamptz default now()
);

create index if not exists idx_movement_shipment_id on public.movement_history(shipment_id);
create index if not exists idx_movement_created_at on public.movement_history(created_at desc);

alter table public.volex enable row level security;
alter table public.shipment enable row level security;
alter table public.movement_history enable row level security;

drop policy if exists "Allow public select on volex" on public.volex;
create policy "Allow public select on volex"
  on public.volex
  for select
  using (true);

drop policy if exists "Allow public insert on volex" on public.volex;
create policy "Allow public insert on volex"
  on public.volex
  for insert
  with check (true);

drop policy if exists "Allow public update on volex" on public.volex;
create policy "Allow public update on volex"
  on public.volex
  for update
  using (true)
  with check (true);

drop policy if exists "Allow public select on shipment" on public.shipment;
create policy "Allow public select on shipment"
  on public.shipment
  for select
  using (true);

drop policy if exists "Allow service writes on shipment" on public.shipment;
create policy "Allow service writes on shipment"
  on public.shipment
  for all
  using (true)
  with check (true);

drop policy if exists "Allow public select on movement_history" on public.movement_history;
create policy "Allow public select on movement_history"
  on public.movement_history
  for select
  using (true);

drop policy if exists "Allow service writes on movement_history" on public.movement_history;
create policy "Allow service writes on movement_history"
  on public.movement_history
  for all
  using (true)
  with check (true);

alter publication supabase_realtime add table public.shipment;
alter publication supabase_realtime add table public.movement_history;
